### ISSUE TITLE
Some cpp cleanup

### ISSUE THREAD

**Issue by sfb103** [jose-acevedoflores/cffi-explore#3]
There are a couple (fairly minor) things that needed some cleanup. 

1) Better not to detach your threads if you can.  Cleaner approach is to cache off their references and join with them in your dtor.  This allows you to ensure all threads are cleaned up when your object is released.  And you don't even need an explicit shutdown call on the class... enjoy having a destructor for a change!

2) You don't need shared_timed_mutex.  You're looking for shared_mutex.  To get that tho, we need to go to C++17 (moving on up :-) ).  BTW, this is also probably why shared_timed_mutex is lacking an example in cppreference.com, i.e. no one really uses it, they use shared_mutex from C++17 instead.  See here for a little background: https://stackoverflow.com/questions/40207171/why-shared-timed-mutex-is-defined-in-c14-but-shared-mutex-in-c17

3) The shared/unique_locks were mostly all deferred and never really locked?  Probably just an oversight.  I put in the more standard way to instantiate these guards. 

4) Refactored how the classes were contained in various cpp/h files.  Made it more standard.  Also put include guards in all the .h's.  Tho #pragma once is more concise, it's not really standard.  I was gonna leave it, but CLion kept putting in include guards and I'm used to that as well.

Hey don't forget, now that we're using cmake, CLion can fully index the libdummy source files.  Forgot to mention that in the last PR.

Rest was really really minor.  Let me know if any of this needs more explanation.

**Comment by jose-acevedoflores** [comment]
See? this is why I need a c++ expert!.

1. I did read about not to do detach so I started down that path using that `//   std::vector<std::thread> ths;` but didn't finish it off.
2. I have no idea why I just picked `C++14`. It did seem odd to me how nobody used that timed mutex haha
3. Yep, I messed up on that one. Didn't mean to use a defer_lock
4. Sweet! I did read about `#pragma` being non standard but it looked so much nicer I couldn't resist.
